// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:56f0f0b9-b769-4528-9dcb-4d194edd3a16",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_UXgYq9P4Q",
    "aws_user_pools_web_client_id": "506b9sls8tq3li5ff9fckv0vsi"
};


export default awsmobile;
